#!/usr/bin/env python3
"""Auto-generated by ``bluei.tools.graduator`` (build-time only).

Self-contained ``DiscoveryPlugin`` pack graduated from an ACTIVE emergent rule.
The ``discover()`` method embeds the rule's DetectionPattern and emits
``Finding`` instances directly — no tool subprocess, no manifest re-read.

Do not hand-edit; re-generate from the source emergent rule. Curated output
is committed to the plugins tree (alpha.5 Pillar 3).
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

# Reach the ``bluei/`` package from the plugins tree (mirrors
# plugins/test/plugin.py:10-12). The committed pack lives at
# ``plugins/<pack_id>/plugin.py`` — same depth as ``plugins/test/plugin.py`` —
# so ``parent.parent.parent`` is the repo root containing ``bluei/``.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from bluei.engine.models import Finding
from bluei.engine.structural_hash import (
    compute_structural_hash,
    fuzzy_structural_match,
    get_fuzzy_threshold,
)
from bluei.app.plugins import DiscoveryPlugin


_PACK_ID = 'graduated-eslint'
_RULE_ID = 'er-eslint-no-console'
_RULE_HEADER = 'Graduated Rule: eslint no-console'
_LANGUAGE = 'javascript'
_CATEGORY = 'lint'
_CONFIDENCE = 0.85
_DETECTION_TYPE = 'regex_pattern'
_SEARCH_PATTERN = 'console\\.(log|debug|info|warn|error)\\b'
_FILE_GLOB = '**/*.js'
_AST_BLOB = None
_EVIDENCE_COUNT = 14

_STRUCTURAL_SUBTREE_CAP = 200
_CONTAINER_KINDS = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def _iter_shadow_files(root: Path, file_glob: str) -> List[Path]:
    globs = [file_glob or "**/*"]
    if file_glob.endswith("/**"):
        globs.append(f"{file_glob}/*")
    files: Dict[str, Path] = {}
    for glob_pattern in globs:
        for path in root.glob(glob_pattern):
            if path.is_file():
                files[path.as_posix()] = path
    return [files[key] for key in sorted(files)]


def _iter_structural_subtrees(tree: ast.AST) -> List[ast.AST]:
    subtrees: List[ast.AST] = []

    def _walk_body(body: list) -> None:
        for node in body:
            if len(subtrees) >= _STRUCTURAL_SUBTREE_CAP:
                return
            if isinstance(node, _CONTAINER_KINDS):
                _walk_body(list(getattr(node, "body", [])))
                continue
            subtrees.append(node)

    _walk_body(list(getattr(tree, "body", [])))
    return subtrees


class Plugin(DiscoveryPlugin):
    """Self-contained detector graduated from emergent rule ``{_RULE_ID}``."""

    @property
    def id(self) -> str:
        return _PACK_ID

    @property
    def name(self) -> str:
        return _RULE_HEADER

    @property
    def languages(self) -> List[str]:
        return [_LANGUAGE]

    @property
    def rules(self) -> List[str]:
        return [_RULE_ID]

    def detect(self, repo_path: Path) -> bool:
        """Applicability: does the detection file glob hit anything?"""
        return any(_iter_shadow_files(Path(repo_path), _FILE_GLOB))

    def discover(self, repo_path: Path, config: Dict[str, Any]) -> List[Finding]:
        """Run the embedded DetectionPattern over the worktree."""
        root = Path(repo_path)
        findings: List[Finding] = []

        if _DETECTION_TYPE == "structural":
            return self._discover_structural(root)

        needle = _SEARCH_PATTERN.strip()
        compiled = None
        if _DETECTION_TYPE == "regex_pattern":
            try:
                compiled = re.compile(needle)
            except re.error:
                return []
        elif _DETECTION_TYPE != "text_pattern":
            return []
        elif not needle:
            return []

        for path in _iter_shadow_files(root, _FILE_GLOB):
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            relative_path = path.relative_to(root).as_posix()
            for index, line in enumerate(text.splitlines(), start=1):
                if compiled is not None:
                    if not compiled.search(line):
                        continue
                elif needle not in line:
                    continue
                findings.append(
                    self._make_finding(
                        relative_path, index, line.strip(), root
                    )
                )
        return findings

    def _discover_structural(self, root: Path) -> List[Finding]:
        blob_raw = _AST_BLOB
        if not blob_raw:
            return []
        try:
            blob = json.loads(blob_raw)
        except (ValueError, TypeError):
            return []
        if not isinstance(blob, dict):
            return []
        target_hash = blob.get("hash")
        canonical = blob.get("canonical_snippet") or ""
        if not target_hash:
            return []
        threshold = get_fuzzy_threshold(_RULE_ID)
        findings: List[Finding] = []
        for path in _iter_shadow_files(root, _FILE_GLOB):
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            try:
                tree = ast.parse(text)
            except (SyntaxError, ValueError):
                continue
            relative_path = path.relative_to(root).as_posix()
            for subtree in _iter_structural_subtrees(tree):
                try:
                    snippet_src = ast.get_source_segment(text, subtree) or ""
                except Exception:
                    snippet_src = ""
                if not snippet_src.strip():
                    continue
                sub_hash = compute_structural_hash(snippet_src, "python")
                is_match = sub_hash == target_hash
                if not is_match and canonical:
                    try:
                        score = fuzzy_structural_match(
                            snippet_src, canonical, "python"
                        )
                    except Exception:
                        score = 0.0
                    is_match = score >= threshold
                if not is_match:
                    continue
                lineno = getattr(subtree, "lineno", 1) or 1
                findings.append(
                    self._make_finding(
                        relative_path, lineno, snippet_src.strip(), root
                    )
                )
        return findings

    @staticmethod
    def _make_finding(
        rel_path: str, line: int, snippet: str, root: Path
    ) -> Finding:
        return Finding(
            finding_id=f"{_RULE_ID}-{rel_path}:{line}",
            repo=str(root),
            path=rel_path,
            line=line,
            rule=_RULE_ID,
            snippet=snippet,
            confidence=_CONFIDENCE,
            quick_win=False,
            safe_to_autofix=False,
            category=_CATEGORY,
        )
